Change CI/CD trigger

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -32,8 +32,20 @@ jobs:
         id: changelog
         run: |
           TAG=${{steps.get_tag.outputs.tag}}
-          CHANGELOG=$(awk "/## ${TAG}/,/^## /" CHANGELOG.txt | sed '1d;$d' || true)
           echo "TAG is ${TAG}"
+          echo "Looking for changelog for tag: $TAG"
+          # Cek apakah ada tag selanjutnya
+          NEXT_LINE=$(grep -n "## ${TAG}" CHANGELOG.txt | cut -d: -f1)
+          if [ -z "$NEXT_LINE" ]; then
+          echo "Tag ${TAG} not found in CHANGELOG.txt"
+          exit 1
+          fi
+          # Ambil isi mulai dari tag hingga sebelum tag berikutnya
+          CHANGELOG=$(awk -v tag="## ${TAG}" '
+          $0 == tag {found=1; next}
+          found && /^## / {exit}
+          found {print}
+          ' CHANGELOG.txt)
           echo "CHANGELOG is ${CHANGELOG}"
           echo "CHANGELOG<<EOF" >> $GITHUB_ENV
           echo "$CHANGELOG" >> $GITHUB_ENV
